"""Camera edge setup command for the Cyberwave CLI."""

import shutil
import subprocess
from pathlib import Path
from typing import Optional

import click
import httpx
from rich.console import Console
from rich.prompt import Prompt

from ..config import (
    ASSETS_ENDPOINT,
    CAMERA_EDGE_DEFAULT_DIR,
    CAMERA_EDGE_REPO_URL,
    ENVIRONMENTS_ENDPOINT,
    TWINS_ENDPOINT,
    get_api_url,
)
from ..credentials import load_credentials

console = Console()


def run_command(cmd: list[str], cwd: Path | None = None) -> bool:
    """Run a shell command and return success status."""
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except Exception:
        return False


def check_git_installed() -> bool:
    """Check if git is installed."""
    return run_command(["git", "--version"])


def create_environment(token: str, name: str, description: str = "") -> Optional[dict]:
    """Create a new environment via the API."""
    try:
        response = httpx.post(
            f"{get_api_url()}{ENVIRONMENTS_ENDPOINT}",
            headers={
                "Authorization": f"Token {token}",
                "Content-Type": "application/json",
            },
            json={
                "name": name,
                "description": description or f"Environment for {name}",
            },
            timeout=30.0,
        )
        if response.status_code in (200, 201):
            return response.json()
        console.print(f"[red]✗[/red] Failed to create environment: {response.text}")
        return None
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating environment: {e}")
        return None


def list_environments(token: str) -> list[dict]:
    """List existing environments via the API."""
    try:
        response = httpx.get(
            f"{get_api_url()}{ENVIRONMENTS_ENDPOINT}",
            headers={
                "Authorization": f"Token {token}",
            },
            timeout=30.0,
        )
        if response.status_code == 200:
            return response.json()
        return []
    except Exception:
        return []


def get_camera_asset(token: str) -> Optional[dict]:
    """Get or find a camera asset from the catalog."""
    try:
        # Try to find a camera asset in the catalog
        response = httpx.get(
            f"{get_api_url()}{ASSETS_ENDPOINT}",
            headers={
                "Authorization": f"Token {token}",
            },
            params={"limit": 100},
            timeout=30.0,
        )
        if response.status_code == 200:
            assets = response.json()
            # Look for an asset with camera-like capabilities or name
            for asset in assets:
                name = asset.get("name", "").lower()
                capabilities = asset.get("capabilities", {}) or {}
                sensors = capabilities.get("sensors", [])

                # Check if it has camera sensors or camera in the name
                has_camera_sensor = any(
                    s.get("type") in ("rgb", "depth", "camera") for s in sensors
                )
                if has_camera_sensor or "camera" in name:
                    return asset

            # If no camera asset found, return the first asset as fallback
            if assets:
                return assets[0]
        return None
    except Exception:
        return None


def create_twin(
    token: str,
    name: str,
    environment_uuid: str,
    asset_uuid: str,
) -> Optional[dict]:
    """Create a new twin via the API."""
    try:
        response = httpx.post(
            f"{get_api_url()}{TWINS_ENDPOINT}",
            headers={
                "Authorization": f"Token {token}",
                "Content-Type": "application/json",
            },
            json={
                "name": name,
                "environment_uuid": environment_uuid,
                "asset_uuid": asset_uuid,
                "capabilities": {"sensors": [{"type": "rgb", "name": "camera"}]},
            },
            timeout=30.0,
        )
        if response.status_code in (200, 201):
            return response.json()
        console.print(f"[red]✗[/red] Failed to create twin: {response.text}")
        return None
    except Exception as e:
        console.print(f"[red]✗[/red] Error creating twin: {e}")
        return None


def write_env_file(
    target_path: Path,
    token: str,
    twin_uuid: str,
    base_url: str | None = None,
) -> bool:
    """Write the .env file with credentials."""
    env_content = f"""# Cyberwave Edge Configuration
# Generated by cyberwave-cli

# Required
CYBERWAVE_TOKEN={token}
CYBERWAVE_TWIN_UUID={twin_uuid}

# Optional
CYBERWAVE_BASE_URL={base_url or get_api_url()}
# CYBERWAVE_EDGE_UUID=edge-device-001
# CAMERA_ID=0
# CAMERA_FPS=10
# LOG_LEVEL=INFO
"""
    try:
        env_file = target_path / ".env"
        env_file.write_text(env_content)
        return True
    except Exception as e:
        console.print(f"[red]✗[/red] Error writing .env file: {e}")
        return False


@click.command()
@click.argument("path", default=CAMERA_EDGE_DEFAULT_DIR, required=False)
@click.option(
    "--environment-uuid",
    "-e",
    help="UUID of an existing environment to use",
)
@click.option(
    "--environment-name",
    "-n",
    help="Name for a new environment (creates one if --environment-uuid not provided)",
)
def camera(path: str, environment_uuid: str | None, environment_name: str | None) -> None:
    """Set up camera edge software for streaming to Cyberwave.

    Clones the cyberwave-edge-python repository and configures it with your
    credentials. You can either use an existing environment or create a new one.

    PATH is the target directory for the project (default: ./cyberwave-camera)

    \b
    Examples:
        cyberwave-cli camera
        cyberwave-cli camera ~/projects/my-camera
        cyberwave-cli camera -e <environment-uuid>
        cyberwave-cli camera -n "My Camera Setup"
    """
    target_path = Path(path).expanduser().resolve()

    # Check authentication
    creds = load_credentials()
    if not creds or not creds.token:
        console.print("\n[red]✗[/red] Not logged in. Run [bold]cyberwave-cli login[/bold] first.")
        raise click.Abort()

    token = creds.token

    # Check if git is installed
    if not check_git_installed():
        console.print("[red]✗[/red] Git is not installed. Please install git first.")
        raise click.Abort()

    # Check if target directory already exists
    if target_path.exists():
        console.print(f"[red]✗[/red] Directory already exists: [bold]{target_path}[/bold]")
        if not click.confirm("Do you want to overwrite it?"):
            raise click.Abort()
        shutil.rmtree(target_path)

    # Handle environment selection/creation
    env_uuid = environment_uuid
    env_name = environment_name

    if not env_uuid:
        # No environment UUID provided, ask user
        console.print("\n[bold]Environment Setup[/bold]")

        # List existing environments
        existing_envs = list_environments(token)

        if existing_envs:
            console.print("\n[dim]Found existing environments:[/dim]")
            for i, env in enumerate(existing_envs[:10], 1):  # Show max 10
                env_display_name = env.get("name", "Unnamed")
                env_display_uuid = env.get("uuid", "")
                console.print(f"  {i}. {env_display_name} [dim]({env_display_uuid})[/dim]")

            choice = Prompt.ask(
                "\n[bold]Enter environment number to use, or press Enter to create new[/bold]",
                default="",
            )

            if choice.strip():
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(existing_envs):
                        env_uuid = existing_envs[idx].get("uuid")
                        env_name = existing_envs[idx].get("name")
                        console.print(
                            f"[green]✓[/green] Using environment: [bold]{env_name}[/bold]"
                        )
                except ValueError:
                    pass

        if not env_uuid:
            # Create new environment
            if not env_name:
                env_name = Prompt.ask(
                    "[bold]Enter name for new environment[/bold]",
                    default="Camera Environment",
                )

            console.print(f"\n[dim]Creating environment '{env_name}'...[/dim]")
            env_data = create_environment(token, env_name)

            if not env_data:
                console.print("[red]✗[/red] Failed to create environment")
                raise click.Abort()

            env_uuid = env_data.get("uuid")
            console.print(f"[green]✓[/green] Created environment: [bold]{env_name}[/bold]")
            console.print(f"[dim]  UUID: {env_uuid}[/dim]")

    # Find or get a camera asset
    console.print("\n[dim]Finding camera asset...[/dim]")
    camera_asset = get_camera_asset(token)

    if not camera_asset:
        console.print(
            "[yellow]⚠[/yellow] No camera asset found in catalog. "
            "The twin will be created without a specific asset."
        )
        # We'll proceed without an asset - the API might accept this or we need a fallback
        asset_uuid = None
    else:
        asset_uuid = camera_asset.get("uuid")
        asset_name = camera_asset.get("name", "Unknown")
        console.print(f"[green]✓[/green] Using asset: [bold]{asset_name}[/bold]")

    # Create a twin for the camera
    twin_name = Prompt.ask(
        "[bold]Enter name for the camera twin[/bold]",
        default="Camera Twin",
    )

    console.print(f"\n[dim]Creating twin '{twin_name}'...[/dim]")

    if asset_uuid:
        twin_data = create_twin(token, twin_name, env_uuid, asset_uuid)
    else:
        console.print("[yellow]⚠[/yellow] Skipping twin creation - no asset available")
        console.print("[dim]You'll need to create a twin manually in the Cyberwave dashboard[/dim]")
        twin_data = None

    if twin_data:
        twin_uuid = twin_data.get("uuid")
        console.print(f"[green]✓[/green] Created twin: [bold]{twin_name}[/bold]")
        console.print(f"[dim]  UUID: {twin_uuid}[/dim]")
    else:
        twin_uuid = Prompt.ask(
            "[bold]Enter existing twin UUID (or create one in dashboard)[/bold]",
            default="",
        )
        if not twin_uuid:
            console.print("[red]✗[/red] Twin UUID is required for camera setup")
            raise click.Abort()

    # Clone the repository
    console.print("\n[bold]Cloning camera edge software...[/bold]")
    console.print(f"[dim]→ {CAMERA_EDGE_REPO_URL}[/dim]")

    result = subprocess.run(
        ["git", "clone", CAMERA_EDGE_REPO_URL, str(target_path)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        console.print("[red]✗[/red] Failed to clone repository")
        console.print(f"[dim]{result.stderr}[/dim]")
        raise click.Abort()

    console.print(f"[green]✓[/green] Cloned to [bold]{target_path}[/bold]")

    # Write the .env file
    console.print("\n[bold]Configuring credentials...[/bold]")
    if write_env_file(target_path, token, twin_uuid):
        console.print("[green]✓[/green] Created .env file with credentials")
    else:
        raise click.Abort()

    # Print success and next steps
    console.print("\n[bold green]✓ Camera setup completed![/bold green]")

    console.print("\n[bold]Environment Details:[/bold]")
    console.print(f"  • Environment: [bold]{env_name or 'Unknown'}[/bold]")
    console.print(f"  • Environment UUID: [dim]{env_uuid}[/dim]")
    console.print(f"  • Twin UUID: [dim]{twin_uuid}[/dim]")

    # Generate environment URL
    base_url = get_api_url().replace("api.", "").replace("/api", "")
    if "localhost" in base_url or "127.0.0.1" in base_url:
        env_url = f"http://localhost:3000/environments/{env_uuid}"
    else:
        env_url = f"https://cyberwave.com/environments/{env_uuid}"

    console.print("\n[bold]View your environment:[/bold]")
    console.print(f"  {env_url}")

    console.print("\n[bold]Next steps:[/bold]")
    console.print(f"  1. [dim]cd {target_path}[/dim]")
    console.print("  2. [dim]pip install -e .[/dim]")
    console.print("  3. [dim]python -m cyberwave_edge.service[/dim]")
    console.print()
    console.print("[dim]Documentation: https://docs.cyberwave.com/edge[/dim]")
